baseURL = "https://dingdl.github.io/dingluo/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Ding Luo"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-173574303-1"

[params]
title = "Ding Luo"
author = "Ding Luo"
description = "PhD | Data Scientist"
profilePicture = "images/p.jpg"
keywords = ""
favicon = "favicons"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dluo/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/dingdl"

[[params.socialIcons]]
icon = "fa-graduation-cap"
title = "GoogleScholar"
url = "https://scholar.google.nl/citations?user=nMzfhAkAAAAJ&hl=en"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:luo.ding@outlook.com"

## Menu items

[menu]

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

[markup.goldmark.renderer]
  unsafe= true # This allows for inserting images with HTML
