baseURL = "https://dingluoweb.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Ding Luo"
theme = "anatole-0.6.0"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreErrors = ["error-remote-getjson"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-173574303-1"

[params]
title = "Ding Luo"
author = "Ding Luo"
description = "PhD | Data Scientist"
profilePicture = "images/p.jpg"
keywords = ""
favicon = ""
customCss = []
customJs = []
mainSections = ["about"]
images = ["images/site-feature-image.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/dluo/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/dingdl"

[[params.socialIcons]]
icon = "fas fa-graduation-cap"
title = "GoogleScholar"
url = "https://scholar.google.nl/citations?user=nMzfhAkAAAAJ&hl=en"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:luo.ding@outlook.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Data Science"
  weight = 300
  identifier = "datascience"
  url = "/datascience/"

  [[menu.main]]
  name = "Research"
  weight = 300
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  # [[menu.main]]
  # name = "Posts"
  # weight = 200
  # identifier = "posts"
  # url = "/post/"

[markup.goldmark.renderer]
  unsafe= true # This allows for inserting images with HTML
